"""empty message

Revision ID: fcc5999aa4fd
Revises: c57efc9ee254
Create Date: 2019-12-31 20:03:31.564809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fcc5999aa4fd'
down_revision = 'c57efc9ee254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_details', sa.Column('line_no', sa.Integer(), nullable=True))
    op.alter_column('order_details', 'line_total',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_details', 'line_total',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('order_details', 'line_no')
    # ### end Alembic commands ###
